name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_EC2_KEY }}

      - name: Copy files to EC2
        run: scp -r -o StrictHostKeyChecking=no ./public/* ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_IP }}:/var/www/html/

      - name: SSH into EC2 and setup Apache
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_IP }} << 'EOF'
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
          sudo chown -R $USER:$USER /var/www
          sudo chmod -R 755 /var/www
          EOF
