name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

    - name: Deploy via rsync
      run: |
        rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./path/to/local/dir/ ubuntu@${{ secrets.HOST_DNS }}:/path/to/remote/dir
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
