name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        run: |
          scp -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no index.html styles.css script.js ubuntu@${{ secrets.HOST_DNS }}:/var/www/html/
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST_DNS: ${{ secrets.HOST_DNS }}
