name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ./index.html ubuntu@35.154.108.203:/var/www/html/index.html
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@35.154.108.203 'sudo systemctl restart apache2'
